// Generated by create-fsd-architecture. Re-run project configuration to update.
export const fsdStack = {
  framework: 'vue-vite',
  frameworkLabel: 'Vue + Vite',
  packageManager: 'npm',
  apiClient: 'axios',
  serverState: 'vue-query',
  clientState: 'pinia',
  forms: 'vee-validate-zod',
  docsUrl: 'https://fsd-docs.vercel.app',
  commands: {
    install: 'npm install',
    dev: 'npm run dev',
    build: 'npm run build',
    generateFeature: 'npx create-fsd-architecture@latest -g feature auth',
    generatePage: 'npx create-fsd-architecture@latest -g page dashboard',
  },
} as const
